# Generated by Django 3.0.4 on 2020-03-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='twilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_account_sid', models.CharField(max_length=40)),
                ('twilio_auth_token', models.CharField(max_length=40)),
            ],
        ),
    ]
